### ISSUE TITLE
compatibility issue of [emoticons][mclib]

### ISSUE THREAD

**Issue by Jecvay** [PaperMC/Waterfall#431]
thanks for reading this.

[server]
spongeforge 1.12.2 7.1.7
waterall-295

[issue mod]
https://www.curseforge.com/minecraft/mc-mods/emoticons
https://www.curseforge.com/minecraft/mc-mods/mchorses-mclib

[issue]
in my server, players can see each other's emoticon without waterfall.
but cannot see after install waterfall in front of spongeforge.
without any error log.

**Comment by mikroskeem** [comment]
Please provide your Waterfall configuration (waterfall.yml) and the list of installed plugins (to rule out other issues). Do you also have IP/profile forwarding enabled (ip_forward in config.yml)?

**Comment by electronicboy** [comment]
Try disabling entity metadata rewriting in waterfall.yml

**Comment by Jecvay** [comment]
> Try disabling entity metadata rewriting in waterfall.yml

thanks. i tried but didn't solve.

> Please provide your Waterfall configuration (waterfall.yml) and the list of installed plugins 

```
use_netty_dns_resolver: true
disable_modern_tab_limiter: true
log_initial_handler_connections: true
throttling:
  tab_complete: 1000
game_version: ''
disable_entity_metadata_rewrite: true
```

```
connection_throttle_limit: 3
online_mode: false
log_commands: false
network_compression_threshold: 256
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
connection_throttle: 4000
groups:
  md_5: null
log_pings: true
ip_forward: true
prevent_proxy_connections: false
forge_support: true
stats: 7a1b5588-dbdb-4fb5-a042-6e0fae11aad2
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default:
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  lobby:
    motd: '&7&l&l&bDHFcraft&7&l qq931292511'
    address: localhost:10000
    restricted: false
  T1:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:10001
    restricted: false
  T2:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:10002
    restricted: false
player_limit: -1
```

plugins of waterfall:
- bungeemotd
- bungeetablistplus2.8.11
- multichat-1.7.3
