### ISSUE TITLE
Jumping disconnects users in FTB modpack

### ISSUE THREAD

**Issue by cooljacob204** [PaperMC/Waterfall#511]
Modpack: https://minecraft.curseforge.com/projects/dimension-zero
Error: https://gist.github.com/cooljacob204/090eb932b66f3fd6fadc107b54a98335

config.yml: 
```
listeners:
- query_port: 25577
  motd: Default server, you probably have the wrong ip
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: true # I tested haproxy directly to make sure it wasn't that
  forced_hosts:
    dimension.lfp2.gg: dimension
    vanilla.lfp2.gg: lobby
    skyblock.lfp2.gg: skyblock
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 30000
timeout: 30000
stats: 4cdf0679-2442-485f-a24d-3673a4df7f78
player_limit: -1
ip_forward: false
groups:
  cooljacob204:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: Vanilla server
    address: 10.0.1.9:25565
    restricted: false
  dimension:
    motd: Dimension!
    address: 10.0.1.11:25565
    restricted: false
  skyblock:
    motd: Skyblock!
    address: 10.0.1.10:25565
    restricted: false
```

waterfall.yml: 
```
use_netty_dns_resolver: false
disable_modern_tab_limiter: true
log_initial_handler_connections: true
throttling:
  tab_complete: 1000
game_version: ''
disable_entity_metadata_rewrite: true
```

And I think it has something to do with this method in this mod:
https://github.com/Daveyx0/PrimitiveMobs/blob/master/src/main/java/net/daveyx0/primitivemobs/message/MessagePrimitiveJumping.java#L37
