### ISSUE TITLE
Modules do not auto download

### ISSUE THREAD

**Issue by RikoDEV** [PaperMC/Waterfall#53]
Bungeecord commands do not work. Displays a command not found.

**My config:**

```
ip_forward: true
network_compression_threshold: 200
stats: d******42-91a5-4d**-b387-2d*******d1e6
permissions:
  default:
  - bungee.helpop.default
  - skinsrestorer.playercmds
  - BungeeBan.Broadcast.Ban
  - BungeeBan.Broadcast.Mute
  - BungeeBan.Broadcast.Unban
  - BungeeBan.Broadcast.Unmute
  admin:
  - bungee.helpop.admin
  - skinsrestorer.cmds
  - skinsrestorer.playercmds
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.ip
  - bungeecord.command.reload
  - serverlistplus.admin
  - bat.admin
  - bat.grantall.global
  helper:
  - bungee.helpop.admin
  - bungeecord.command.list
  - bat.admin
  - bat.grantall.global
groups:
  Polski*****:
  - admin
  K*****:
  - admin
  Xa****L:
  - helper
  bosco:
  - helper
servers:
  survival:
    address: localhost:255**
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  skywars:
    address: localhost:255**
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  lobby:
    address: localhost:255**
    restricted: false
    motd: '***'
  creative:
    address: localhost:255**
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  skyblock:
    address: localhost:255**
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
timeout: 30000
listeners:
- query_port: ****
  motd: '*****'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: true
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 100
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
online_mode: false
player_limit: 100
custom_server_name: CUBECORD
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
```
