### ISSUE TITLE
Config.yml line order gets shuffled around on every start

### ISSUE THREAD

**Issue by femboyfin** [PaperMC/Waterfall#665]
On every startup my config.yml gets shuffled around, I'm not sure if this is intentional or not but it's a bit annoying. I'll put an example below, the particular entries that move are `server_connect_timeout`, `prevent_proxy_connections`, and `stats`.

Before:
```
server_connect_timeout: 5000
listeners:
- max_players: 69
  host: ip:port
  bind_local_address: true
  ping_passthrough: true
  tab_list: GLOBAL_PING
  tab_size: 60
  forced_hosts:
    example.com: survival
    creative.example.com: creative
  priorities:
  - survival
  - creative
  force_default_server: false
  motd: motd
  query_enabled: false
  proxy_protocol: false
  query_port: port
remote_ping_cache: -1
network_compression_threshold: 512
permissions:
  default:
  - bungeecord.command.server
log_pings: true
connection_throttle_limit: 5
prevent_proxy_connections: true
timeout: 30000
player_limit: 100
ip_forward: true
groups:
  bigfinfrank:
  - default
remote_ping_timeout: 5000
connection_throttle: 5000
log_commands: true
stats: 00000000-0000-0000-0000-000000000000
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  survival:
    motd: motd
    address: ip:port
    restricted: false
  creative:
    motd: motd
    address: ip:port
    restricted: true

```

After:
```
listeners:
- max_players: 69
  host: ip:port
  bind_local_address: true
  ping_passthrough: true
  tab_list: GLOBAL_PING
  tab_size: 60
  forced_hosts:
    example.com: survival
    creative.example.com: creative
  priorities:
  - survival
  - creative
  force_default_server: false
  motd: motd
  query_enabled: false
  proxy_protocol: false
  query_port: port
remote_ping_cache: -1
network_compression_threshold: 512
permissions:
  default:
  - bungeecord.command.server
log_pings: true
connection_throttle_limit: 5
server_connect_timeout: 5000
timeout: 30000
stats: 00000000-0000-0000-0000-000000000000
player_limit: 100
ip_forward: true
groups:
  bigfinfrank:
  - default
remote_ping_timeout: 5000
connection_throttle: 5000
log_commands: true
prevent_proxy_connections: true
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  survival:
    motd: motd
    address: ip:port
    restricted: false
  creative:
    motd: motd
    address: ip:port
    restricted: true
```
